language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install pep8
script:
  - pep8 generate.py
  - mkdir -p tmp
  - python generate.py -l DEBUG -c conf.yaml tmp
